import { ResizePreset } from '../types';

export const RESIZE_PRESETS: ResizePreset[] = [
  // 1. Google Play & Android
  {
    id: 'gp-icon',
    category: 'google-play',
    nameAr: 'أيقونة متجر Google Play',
    nameEn: 'Google Play App Icon',
    width: 512,
    height: 512,
    aspectRatio: '1:1',
    defaultFormat: 'png',
    descriptionAr: 'الأيقونة الرسمية المطلوبة بتنسيق PNG أو WEBP بدقة 512x512 بكسل وحجم أقل من 1MB.',
    descriptionEn: 'Official 512x512 px PNG or WEBP app icon for Google Play Store listing.',
    badge: 'PLAY STORE',
  },
  {
    id: 'gp-feature',
    category: 'google-play',
    nameAr: 'الرسم المميز لمتجر Google Play',
    nameEn: 'Google Play Feature Graphic',
    width: 1024,
    height: 500,
    aspectRatio: '1024:500',
    defaultFormat: 'png',
    descriptionAr: 'الرسم المميز الترويجي بدقة 1024 × 500 بكسل المطلوب رسمياً لإبراز تطبيقك على المتجر.',
    descriptionEn: 'Official 1,024 x 500 px promotional graphic used across Google Play Store.',
    badge: '1024×500',
  },
  {
    id: 'gp-promo',
    category: 'google-play',
    nameAr: 'الرسم الترويجي المصغر',
    nameEn: 'Google Play Promo Graphic',
    width: 180,
    height: 120,
    aspectRatio: '3:2',
    defaultFormat: 'png',
    descriptionAr: 'رسم ترويجي مصغر للعروض والمجموعات المختارة.',
    descriptionEn: 'Small promo banner for Play store collections and promotions.',
  },
  {
    id: 'gp-tv-banner',
    category: 'google-play',
    nameAr: 'بانر تلفزيون Android TV',
    nameEn: 'Android TV Banner',
    width: 1280,
    height: 720,
    aspectRatio: '16:9',
    defaultFormat: 'png',
    descriptionAr: 'بانر رئيسي لشاشات أجهزة Android TV بدقة HD 720p.',
    descriptionEn: 'HD 1280x720 banner for Android TV and Google TV platforms.',
  },
  {
    id: 'gp-screenshot-phone',
    category: 'google-play',
    nameAr: 'لقطة شاشة الهاتف المحمول',
    nameEn: 'Phone App Screenshot',
    width: 1080,
    height: 1920,
    aspectRatio: '9:16',
    defaultFormat: 'png',
    descriptionAr: 'لقطات شاشة تطبيقات الهواتف الذكية بنسبة 9:16 بدقة Full HD.',
    descriptionEn: 'Standard 1080x1920 Full HD phone screenshots for Play Store.',
  },
  {
    id: 'gp-screenshot-tab-10',
    category: 'google-play',
    nameAr: 'لقطة شاشة جهاز لوحي 10 بوصة',
    nameEn: '10-inch Tablet Screenshot',
    width: 1600,
    height: 2560,
    aspectRatio: '10:16',
    defaultFormat: 'png',
    descriptionAr: 'لقطات شاشة مخصصة للأجهزة اللوحية الكبيرة 10 Inch.',
    descriptionEn: 'High-res 1600x2560 screenshot for 10-inch tablets.',
  },
  {
    id: 'gp-wear-os',
    category: 'google-play',
    nameAr: 'أيقونة ساعات Wear OS',
    nameEn: 'Wear OS Watch Icon',
    width: 512,
    height: 512,
    aspectRatio: '1:1',
    defaultFormat: 'png',
    descriptionAr: 'أيقونة تطبيقات الساعات الذكية بنظام Wear OS.',
    descriptionEn: 'App icon for Android Wear OS smartwatches.',
  },

  // 2. Apple App Store & iOS / macOS
  {
    id: 'ios-app-store',
    category: 'app-store',
    nameAr: 'أيقونة متجر App Store (1024×1024)',
    nameEn: 'App Store Icon (1024x1024)',
    width: 1024,
    height: 1024,
    aspectRatio: '1:1',
    defaultFormat: 'png',
    descriptionAr: 'الأيقونة الرسمية الكبرى المطلوبة لرفع التطبيق على Apple App Store (بدون شفافية).',
    descriptionEn: 'Official 1024x1024 px PNG icon required for App Store Connect submission.',
    badge: 'APP STORE',
  },
  {
    id: 'ios-iphone-icon-3x',
    category: 'app-store',
    nameAr: 'أيقونة iPhone Retina (60pt @3x)',
    nameEn: 'iPhone App Icon (@3x)',
    width: 180,
    height: 180,
    aspectRatio: '1:1',
    defaultFormat: 'png',
    descriptionAr: 'شاشة الآيفون الرئيسية عالية الكثافة (iPhone 15 / 14 / Pro Max).',
    descriptionEn: 'iPhone home screen app icon for Super Retina display (@3x 180px).',
  },
  {
    id: 'ios-iphone-icon-2x',
    category: 'app-store',
    nameAr: 'أيقونة iPhone Retina (60pt @2x)',
    nameEn: 'iPhone App Icon (@2x)',
    width: 120,
    height: 120,
    aspectRatio: '1:1',
    defaultFormat: 'png',
    descriptionAr: 'شاشات الآيفون القياسية ريتينا (iPhone standard @2x).',
    descriptionEn: 'iPhone home screen app icon for Retina display (@2x 120px).',
  },
  {
    id: 'ios-ipad-pro',
    category: 'app-store',
    nameAr: 'أيقونة iPad Pro (83.5pt @2x)',
    nameEn: 'iPad Pro App Icon',
    width: 167,
    height: 167,
    aspectRatio: '1:1',
    defaultFormat: 'png',
    descriptionAr: 'أيقونة شاشة أجهزة iPad Pro اللوحية الحديثة.',
    descriptionEn: 'App icon for iPad Pro 12.9" and 11" screens.',
  },
  {
    id: 'ios-ipad',
    category: 'app-store',
    nameAr: 'أيقونة iPad القياسية (76pt @2x)',
    nameEn: 'iPad Air / Mini Icon',
    width: 152,
    height: 152,
    aspectRatio: '1:1',
    defaultFormat: 'png',
    descriptionAr: 'أيقونة شاشة أجهزة iPad و iPad Mini.',
    descriptionEn: 'App icon for standard iPad and iPad mini devices.',
  },
  {
    id: 'macos-app-512',
    category: 'app-store',
    nameAr: 'أيقونة نظام macOS (512×512)',
    nameEn: 'macOS App Icon',
    width: 512,
    height: 512,
    aspectRatio: '1:1',
    defaultFormat: 'png',
    descriptionAr: 'أيقونة شريط التطبيقات Dock وشاشات Mac.',
    descriptionEn: 'Standard 512x512 app icon for Mac Dock & Finder.',
  },
  {
    id: 'macos-app-1024',
    category: 'app-store',
    nameAr: 'أيقونة نظام macOS Retina (1024×1024)',
    nameEn: 'macOS Retina Icon',
    width: 1024,
    height: 1024,
    aspectRatio: '1:1',
    defaultFormat: 'png',
    descriptionAr: 'أيقونة شاشات Mac Retina بدقة 5K و 4K فائقة الوضوح.',
    descriptionEn: 'Ultra-high-res 1024x1024 icon for macOS 5K/Retina displays.',
  },
  {
    id: 'ios-imessage',
    category: 'app-store',
    nameAr: 'تطبيقات متجر iMessage',
    nameEn: 'iMessage App Icon',
    width: 1024,
    height: 768,
    aspectRatio: '4:3',
    defaultFormat: 'png',
    descriptionAr: 'أيقونة تطبيقات وملصقات رسائل iMessage في متجر آبل.',
    descriptionEn: 'App icon for iMessage stickers and apps in Apple Store.',
  },

  // 3. Web & Favicons & PWA
  {
    id: 'web-fav-16',
    category: 'web-favicon',
    nameAr: 'أيقونة المتصفح المصغرة 16×16',
    nameEn: 'Favicon Standard (16x16)',
    width: 16,
    height: 16,
    aspectRatio: '1:1',
    defaultFormat: 'ico',
    descriptionAr: 'الأيقونة الكلاسيكية الصغيرة لتبويب المتصفحات وعناوين URL.',
    descriptionEn: 'Classic tiny browser tab favicon.',
  },
  {
    id: 'web-fav-32',
    category: 'web-favicon',
    nameAr: 'أيقونة المتصفح عالية الدقة 32×32',
    nameEn: 'Favicon Retina (32x32)',
    width: 32,
    height: 32,
    aspectRatio: '1:1',
    defaultFormat: 'ico',
    descriptionAr: 'الأيقونة القياسية لجميع شاشات الحواسيب والمتصفحات الحديثة.',
    descriptionEn: 'Standard crisp browser tab icon for modern monitors.',
  },
  {
    id: 'web-fav-48',
    category: 'web-favicon',
    nameAr: 'أيقونة شريط المهام 48×48',
    nameEn: 'Taskbar / Desktop Favicon (48x48)',
    width: 48,
    height: 48,
    aspectRatio: '1:1',
    defaultFormat: 'png',
    descriptionAr: 'أيقونة التثبيت في شريط المهام بنظام Windows.',
    descriptionEn: 'Windows taskbar & desktop shortcut icon.',
  },
  {
    id: 'web-fav-180',
    category: 'web-favicon',
    nameAr: 'أيقونة آبل للمواقع Apple Touch (180×180)',
    nameEn: 'Apple Touch Icon (180x180)',
    width: 180,
    height: 180,
    aspectRatio: '1:1',
    defaultFormat: 'png',
    descriptionAr: 'تظهر عند إضافة الموقع إلى الشاشة الرئيسية في Safari و iPhone.',
    descriptionEn: 'Saved website shortcut on iPhone & iPad home screens.',
  },
  {
    id: 'web-fav-192',
    category: 'web-favicon',
    nameAr: 'أيقونة PWA أندرويد (192×192)',
    nameEn: 'Android Chrome PWA (192x192)',
    width: 192,
    height: 192,
    aspectRatio: '1:1',
    defaultFormat: 'png',
    descriptionAr: 'أيقونة تطبيقات الويب التقدمية PWA على شاشات هواتف أندرويد.',
    descriptionEn: 'Standard Android Chrome Progressive Web App icon.',
  },
  {
    id: 'web-fav-512',
    category: 'web-favicon',
    nameAr: 'شاشة البداية PWA Splash (512×512)',
    nameEn: 'PWA Splash Screen Icon (512x512)',
    width: 512,
    height: 512,
    aspectRatio: '1:1',
    defaultFormat: 'png',
    descriptionAr: 'شاشة التحميل والترحيب لتطبيقات الويب PWA بدقة فائقة.',
    descriptionEn: 'High-res PWA splash & launcher icon.',
  },
  {
    id: 'web-og-image',
    category: 'web-favicon',
    nameAr: 'صورة المشاركة الاجتماعية OpenGraph (1200×630)',
    nameEn: 'OpenGraph Share Image (1200x630)',
    width: 1200,
    height: 630,
    aspectRatio: '1.91:1',
    defaultFormat: 'jpeg',
    descriptionAr: 'الصورة التي تظهر تلقائياً عند مشاركة رابط الموقع على واتساب وفيسبوك ولينكدإن.',
    descriptionEn: 'Social preview banner for link shares on WhatsApp, FB, and LinkedIn.',
    badge: 'SOCIAL SHARE',
  },
  {
    id: 'web-twitter-card',
    category: 'web-favicon',
    nameAr: 'بطاقة تويتر Twitter Card (1200×600)',
    nameEn: 'Twitter Card Preview (1200x600)',
    width: 1200,
    height: 600,
    aspectRatio: '2:1',
    defaultFormat: 'jpeg',
    descriptionAr: 'بطاقة معاينة الروابط الكبيرة في موقع X / Twitter.',
    descriptionEn: 'Large Twitter summary card preview image.',
  },

  // 4. Social Media & Ads
  {
    id: 'ig-post-square',
    category: 'social-media',
    nameAr: 'منشور إنستغرام مربع (1080×1080)',
    nameEn: 'Instagram Square Post (1080x1080)',
    width: 1080,
    height: 1080,
    aspectRatio: '1:1',
    defaultFormat: 'jpeg',
    descriptionAr: 'المنشور المربع الكلاسيكي لإنستغرام وفيسبوك.',
    descriptionEn: 'Standard 1:1 square post for Instagram and Facebook feed.',
  },
  {
    id: 'ig-story-reel',
    category: 'social-media',
    nameAr: 'ستوري وريلز إنستغرام وتيك توك (1080×1920)',
    nameEn: 'Instagram Story / Reel (1080x1920)',
    width: 1080,
    height: 1920,
    aspectRatio: '9:16',
    defaultFormat: 'jpeg',
    descriptionAr: 'قصص وريلز إنستغرام، تيك توك، وسناب شات وواتساب ستاتس.',
    descriptionEn: 'Full screen vertical 9:16 format for Stories, Reels, and TikTok.',
  },
  {
    id: 'ig-portrait',
    category: 'social-media',
    nameAr: 'منشور إنستغرام عمودي (1080×1350)',
    nameEn: 'Instagram Portrait Post (1080x1350)',
    width: 1080,
    height: 1350,
    aspectRatio: '4:5',
    defaultFormat: 'jpeg',
    descriptionAr: 'منشور عمودي يحتل أكبر مساحة رؤية في خلاصة إنستغرام.',
    descriptionEn: '4:5 vertical portrait post for maximum screen engagement.',
  },
  {
    id: 'yt-thumb',
    category: 'social-media',
    nameAr: 'صورة يوتيوب المصغرة Thumbnail (1280×720)',
    nameEn: 'YouTube Thumbnail (1280x720)',
    width: 1280,
    height: 720,
    aspectRatio: '16:9',
    defaultFormat: 'jpeg',
    descriptionAr: 'الصورة المصغرة القياسية عالية الدقة لمقاطع فيديو YouTube.',
    descriptionEn: 'HD 16:9 video thumbnail for YouTube.',
  },
  {
    id: 'yt-banner',
    category: 'social-media',
    nameAr: 'غلاف قناة يوتيوب Channel Banner (2560×1440)',
    nameEn: 'YouTube Channel Banner (2560x1440)',
    width: 2560,
    height: 1440,
    aspectRatio: '16:9',
    defaultFormat: 'jpeg',
    descriptionAr: 'غلاف القناة الرئيسي الذي يظهر على شاشات التلفزيون والحواسيب.',
    descriptionEn: 'High-res channel header art for YouTube across all devices.',
  },
  {
    id: 'x-header',
    category: 'social-media',
    nameAr: 'غلاف حساب X / Twitter (1500×500)',
    nameEn: 'X / Twitter Header (1500x500)',
    width: 1500,
    height: 500,
    aspectRatio: '3:1',
    defaultFormat: 'jpeg',
    descriptionAr: 'البانر العلوي لحسابات تويتر / منصة X.',
    descriptionEn: 'Header banner for X (Twitter) profile pages.',
  },
  {
    id: 'x-post',
    category: 'social-media',
    nameAr: 'صورة تغريدة X / Twitter (1600×900)',
    nameEn: 'X / Twitter Post (1600x900)',
    width: 1600,
    height: 900,
    aspectRatio: '16:9',
    defaultFormat: 'jpeg',
    descriptionAr: 'منشورات وتغريدات منصة X بنسبة 16:9 واضحة وبراقة.',
    descriptionEn: 'In-stream image post for X / Twitter.',
  },
  {
    id: 'fb-cover',
    category: 'social-media',
    nameAr: 'غلاف صفحة فيسبوك Facebook Cover (820×312)',
    nameEn: 'Facebook Page Cover (820x312)',
    width: 820,
    height: 312,
    aspectRatio: '2.63:1',
    defaultFormat: 'jpeg',
    descriptionAr: 'الغلاف العلوي لصفحات ومجموعات فيسبوك.',
    descriptionEn: 'Header banner for Facebook pages and groups.',
  },
  {
    id: 'li-banner',
    category: 'social-media',
    nameAr: 'غلاف صفحة لينكدإن LinkedIn Banner (1584×396)',
    nameEn: 'LinkedIn Company Banner (1584x396)',
    width: 1584,
    height: 396,
    aspectRatio: '4:1',
    defaultFormat: 'jpeg',
    descriptionAr: 'الغلاف الاحترافي لصفحات الشركات والحسابات الشخصية على LinkedIn.',
    descriptionEn: 'Background banner for LinkedIn profiles and company pages.',
  },
  {
    id: 'social-avatar-square',
    category: 'social-media',
    nameAr: 'الصورة الشخصية لجميع المنصات (500×500)',
    nameEn: 'Universal Avatar / Profile Pic (500x500)',
    width: 500,
    height: 500,
    aspectRatio: '1:1',
    defaultFormat: 'png',
    descriptionAr: 'صورة الحساب الشخصي لإنستغرام، واتساب، تلغرام، تيك توك، وتويتر.',
    descriptionEn: 'Crisp profile avatar for WhatsApp, Telegram, Instagram, and TikTok.',
  },

  // 5. Print & Standard Paper Sizes
  {
    id: 'print-a4',
    category: 'print-paper',
    nameAr: 'ورق طباعة A4 عالي الدقة (300 DPI)',
    nameEn: 'A4 Paper (300 DPI Print)',
    width: 2480,
    height: 3508,
    aspectRatio: '1:1.414',
    defaultFormat: 'png',
    descriptionAr: 'مقاس الورق القياسي A4 (210 × 297 مم) بدقة 300 DPI فائقة للطباعة.',
    descriptionEn: 'Standard A4 paper (210 x 297 mm) rendered at high-resolution 300 DPI.',
    badge: '300 DPI',
  },
  {
    id: 'print-a5',
    category: 'print-paper',
    nameAr: 'ورق طباعة A5 (300 DPI)',
    nameEn: 'A5 Paper (300 DPI)',
    width: 1748,
    height: 2480,
    aspectRatio: '1:1.414',
    defaultFormat: 'png',
    descriptionAr: 'مقاس الكتيبات والبروشورات A5 (148 × 210 مم) بدقة 300 DPI.',
    descriptionEn: 'Standard A5 booklet/flyer size at 300 DPI.',
  },
  {
    id: 'print-bcard',
    category: 'print-paper',
    nameAr: 'بطاقة أعمال كارت شخصي Business Card (300 DPI)',
    nameEn: 'Business Card (3.5" x 2" @ 300 DPI)',
    width: 1050,
    height: 600,
    aspectRatio: '3.5:2',
    defaultFormat: 'png',
    descriptionAr: 'كارت العمل التجاري القياسي (89 × 51 مم) بدقة طباعة 300 DPI.',
    descriptionEn: 'Standard 3.5" x 2" business card size at 300 DPI.',
  },
  {
    id: 'print-poster-hd',
    category: 'print-paper',
    nameAr: 'شاشة Full HD 1080p (1920×1080)',
    nameEn: 'Full HD 1080p (1920x1080)',
    width: 1920,
    height: 1080,
    aspectRatio: '16:9',
    defaultFormat: 'png',
    descriptionAr: 'خلفيات الشاشات والعروض التقديمية بدقة 1080p.',
    descriptionEn: '1080p widescreen presentation & desktop wallpaper.',
  },
  {
    id: 'print-poster-4k',
    category: 'print-paper',
    nameAr: 'شاشة ودقة فائقة 4K Ultra HD (3840×2160)',
    nameEn: '4K Ultra HD (3840x2160)',
    width: 3840,
    height: 2160,
    aspectRatio: '16:9',
    defaultFormat: 'png',
    descriptionAr: 'دقة 4K فائقة الوضوح للشاشات والبوسترات الكبيرة.',
    descriptionEn: '4K UHD wallpaper & large format printing.',
    badge: '4K UHD',
  },
];
