import { Template, LogoConfig } from '../types';

export const DEFAULT_LOGO_CONFIG: LogoConfig = {
  id: 'default_project',
  // Empty so the UI falls back to the translated 'Untitled project'.
  name: '',
  updatedAt: Date.now(),
  canvasSize: 512,
  padding: 32,
  
  bgType: 'linear',
  bgColor1: '#0f172a',
  bgColor2: '#1e1b4b',
  bgGradientAngle: 135,
  pattern: 'none',
  patternOpacity: 0.15,
  shapeMask: 'squircle',
  borderRadius: 48,
  
  borderWidth: 2,
  borderColor: 'rgba(255, 255, 255, 0.12)',
  borderStyle: 'solid',
  shadowBlur: 24,
  shadowColor: 'rgba(0, 0, 0, 0.4)',
  shadowOffsetY: 12,
  innerGlow: true,
  innerGlowColor: '#38bdf8',
  
  iconType: 'library',
  iconKey: 'cpu',
  iconSize: 180,
  iconColor: '#38bdf8',
  iconColor2: '#818cf8',
  iconGradient: true,
  iconGradientAngle: 135,
  iconOffsetX: 0,
  iconOffsetY: 0,
  iconRotation: 0,
  iconFlipH: false,
  iconFlipV: false,
  iconOpacity: 1,
  iconShadow: false,
  iconShadowColor: 'rgba(0, 0, 0, 0.5)',
  iconShadowBlur: 8,
  iconShadowOffsetX: 0,
  iconShadowOffsetY: 4,
  iconOutline: false,
  iconOutlineWidth: 3,
  iconOutlineColor: '#ffffff',
  
  uploadedImageScale: 100,
  uploadedImageOffsetX: 0,
  uploadedImageOffsetY: 0,
  uploadedImageRotation: 0,
  uploadedImageOpacity: 1,
  uploadedImageCropShape: 'squircle',
  uploadedImageFilters: {
    brightness: 100,
    contrast: 100,
    saturation: 100,
    hueRotate: 0,
    grayscale: 0,
    invert: 0,
    sepia: 0,
    blur: 0,
  },
  
  showText: true,
  // Filled from the locale when a blank project is created (see App).
  text: '',
  fontFamily: 'Cairo',
  fontSize: 44,
  fontWeight: 800,
  textColor: '#ffffff',
  textColor2: '#cbd5e1',
  textGradient: false,
  textGradientAngle: 90,
  letterSpacing: 1,
  textLineHeight: 1.2,
  textTransform: 'none',
  textOffsetX: 0,
  textOffsetY: 0,
  textRotation: 0,
  textCurve: 'straight',
  textCurveRadius: 180,
  textShadow: true,
  textShadowColor: 'rgba(0, 0, 0, 0.5)',
  textShadowBlur: 6,
  textShadowOffsetX: 0,
  textShadowOffsetY: 4,
  textStroke: false,
  textStrokeWidth: 2,
  textStrokeColor: '#000000',
  textUppercase: false,
  
  showTagline: true,
  tagline: '',
  taglineFontFamily: 'Tajawal',
  taglineFontSize: 16,
  taglineFontWeight: 500,
  taglineColor: '#94a3b8',
  taglineLetterSpacing: 2,
  taglineOffsetY: 0,
  taglineUppercase: false,
  
  showRing: false,
  ringRadius: 210,
  ringWidth: 3,
  ringColor: '#38bdf8',
  ringDash: false,
  
  showBadgeRibbon: false,
  layout: 'icon-top',
  watermark: {
    enabled: false,
    type: 'text',
    text: 'CONFIDENTIAL',
    opacity: 0.25,
    position: 'bottom-right',
    size: 24,
    rotation: 0,
    color: '#ffffff',
    fontFamily: 'Cairo',
    fontSize: 18,
  },
};

export const TEMPLATES: Template[] = [
  // 0. Fyntica Financial Analytics (Inspired by user's uploaded sample)
  {
    id: 'fyntica-finance',
    nameAr: 'فينتيكا للتحليلات المالية',
    nameEn: 'Fyntica Finance Analytics',
    category: 'corporate',
    categoryLabelAr: 'مالية وتقارير',
    categoryLabelEn: 'Finance & Reports',
    config: {
      bgType: 'linear',
      bgColor1: '#0d9488',
      bgColor2: '#0f766e',
      bgGradientAngle: 135,
      shapeMask: 'squircle',
      borderRadius: 56,
      borderWidth: 3,
      borderColor: 'rgba(255, 255, 255, 0.4)',
      innerGlow: true,
      innerGlowColor: '#5eead4',
      iconKey: 'chart',
      iconSize: 185,
      iconColor: '#ffffff',
      iconColor2: '#ccfbf1',
      iconGradient: false,
      iconShadow: true,
      iconShadowColor: 'rgba(0, 0, 0, 0.35)',
      iconShadowBlur: 10,
      iconShadowOffsetY: 6,
      text: 'Fyntica',
      fontFamily: 'Outfit',
      fontSize: 48,
      fontWeight: 800,
      textColor: '#ffffff',
      textShadow: true,
      textShadowColor: 'rgba(0, 0, 0, 0.45)',
      textShadowBlur: 8,
      textShadowOffsetY: 4,
      showTagline: false,
      tagline: 'SMART FINANCIAL ANALYTICS',
      layout: 'icon-top',
    },
  },
  // 1. Tech & AI Nova
  {
    id: 'tech-quantum',
    nameAr: 'كوانتوم للذكاء الاصطناعي',
    nameEn: 'Quantum AI Tech',
    category: 'tech',
    categoryLabelAr: 'تقنية وذكاء اصطناعي',
    categoryLabelEn: 'Tech & AI',
    config: {
      bgType: 'linear',
      bgColor1: '#090d16',
      bgColor2: '#111827',
      bgGradientAngle: 145,
      shapeMask: 'squircle',
      borderRadius: 48,
      borderWidth: 2,
      borderColor: 'rgba(56, 189, 248, 0.3)',
      innerGlow: true,
      innerGlowColor: '#38bdf8',
      iconKey: 'atom',
      iconSize: 175,
      iconColor: '#38bdf8',
      iconColor2: '#818cf8',
      iconGradient: true,
      text: 'QUANTUM',
      fontFamily: 'Outfit',
      fontSize: 40,
      fontWeight: 800,
      textColor: '#ffffff',
      letterSpacing: 4,
      textUppercase: true,
      showTagline: true,
      tagline: 'NEXT-GEN INTELLIGENCE',
      taglineFontFamily: 'Outfit',
      taglineFontSize: 14,
      taglineColor: '#38bdf8',
      taglineLetterSpacing: 4,
      layout: 'icon-top',
    },
  },

  // 2. Arabic Tech
  {
    id: 'arabic-sadeem',
    nameAr: 'سديم للحوسبة السحابية',
    nameEn: 'Sadeem Cloud Tech',
    category: 'tech',
    categoryLabelAr: 'تقنية وذكاء اصطناعي',
    categoryLabelEn: 'Tech & AI',
    config: {
      bgType: 'linear',
      bgColor1: '#0f172a',
      bgColor2: '#312e81',
      bgGradientAngle: 120,
      shapeMask: 'squircle',
      borderRadius: 50,
      borderWidth: 2,
      borderColor: 'rgba(129, 140, 248, 0.4)',
      innerGlow: true,
      innerGlowColor: '#818cf8',
      iconKey: 'cloud-data',
      iconSize: 180,
      iconColor: '#67e8f9',
      iconColor2: '#a855f7',
      iconGradient: true,
      text: 'سـديم',
      fontFamily: 'Cairo',
      fontSize: 48,
      fontWeight: 900,
      textColor: '#ffffff',
      letterSpacing: 2,
      showTagline: true,
      tagline: 'منصة الحوسبة الذكية',
      taglineFontFamily: 'Tajawal',
      taglineFontSize: 16,
      taglineColor: '#93c5fd',
      taglineLetterSpacing: 1,
      layout: 'icon-top',
    },
  },

  // 3. Cyber Rocket
  {
    id: 'cyber-rocket',
    nameAr: 'انطلاق للشركات الناشئة',
    nameEn: 'Veloce Startup Rocket',
    category: 'tech',
    categoryLabelAr: 'تقنية وذكاء اصطناعي',
    categoryLabelEn: 'Tech & AI',
    config: {
      bgType: 'linear',
      bgColor1: '#18181b',
      bgColor2: '#09090b',
      bgGradientAngle: 180,
      shapeMask: 'circle',
      borderWidth: 3,
      borderColor: '#f43f5e',
      iconKey: 'rocket',
      iconSize: 170,
      iconColor: '#fb7185',
      iconColor2: '#f43f5e',
      iconGradient: true,
      text: 'VELOCE',
      fontFamily: 'Montserrat',
      fontSize: 42,
      fontWeight: 900,
      textColor: '#ffffff',
      letterSpacing: 3,
      showTagline: true,
      tagline: 'ACCELERATE GROWTH',
      taglineFontFamily: 'Outfit',
      taglineFontSize: 13,
      taglineColor: '#fb7185',
      taglineLetterSpacing: 3,
      layout: 'icon-top',
    },
  },

  // 4. Royal Luxury Crown
  {
    id: 'luxury-royal',
    nameAr: 'التاج الملكي الفاخر',
    nameEn: 'Royal Crown Luxury',
    category: 'luxury',
    categoryLabelAr: 'فخامة وملكية',
    categoryLabelEn: 'Luxury & Royal',
    config: {
      bgType: 'linear',
      bgColor1: '#18140c',
      bgColor2: '#0c0a06',
      bgGradientAngle: 135,
      shapeMask: 'shield',
      borderWidth: 2,
      borderColor: '#eab308',
      innerGlow: true,
      innerGlowColor: '#fde047',
      iconKey: 'crown-royal',
      iconSize: 170,
      iconColor: '#facc15',
      iconColor2: '#ca8a04',
      iconGradient: true,
      text: 'ROYALE',
      fontFamily: 'Playfair Display',
      fontSize: 42,
      fontWeight: 700,
      textColor: '#fef08a',
      letterSpacing: 6,
      textUppercase: true,
      showTagline: true,
      tagline: 'PREMIUM HERITAGE',
      taglineFontFamily: 'Montserrat',
      taglineFontSize: 13,
      taglineColor: '#ca8a04',
      taglineLetterSpacing: 4,
      layout: 'icon-top',
    },
  },

  // 5. Arabic Luxury Gold
  {
    id: 'arabic-deem-gold',
    nameAr: 'دار الفخامة الذهبية',
    nameEn: 'Dar Al-Fakhama Gold',
    category: 'luxury',
    categoryLabelAr: 'فخامة وملكية',
    categoryLabelEn: 'Luxury & Royal',
    config: {
      bgType: 'linear',
      bgColor1: '#171717',
      bgColor2: '#0a0a0a',
      bgGradientAngle: 90,
      shapeMask: 'octagon',
      borderWidth: 2.5,
      borderColor: '#d97706',
      showRing: true,
      ringRadius: 215,
      ringWidth: 1.5,
      ringColor: '#f59e0b',
      iconKey: 'diamond-gem',
      iconSize: 160,
      iconColor: '#fbbf24',
      iconColor2: '#d97706',
      iconGradient: true,
      text: 'المجلس',
      fontFamily: 'Cairo',
      fontSize: 46,
      fontWeight: 800,
      textColor: '#fde68a',
      letterSpacing: 2,
      showTagline: true,
      tagline: 'للضيافة والاستشارات الراقية',
      taglineFontFamily: 'Tajawal',
      taglineFontSize: 15,
      taglineColor: '#d97706',
      taglineLetterSpacing: 1,
      layout: 'icon-top',
    },
  },

  // 6. Minimal Monogram S
  {
    id: 'minimal-monogram',
    nameAr: 'حرف المونوغرام الأنيق',
    nameEn: 'Minimal Monogram Studio',
    category: 'minimal',
    categoryLabelAr: 'بسيط وأحادي',
    categoryLabelEn: 'Minimal & Monogram',
    config: {
      bgType: 'solid',
      bgColor1: '#09090b',
      shapeMask: 'circle',
      borderWidth: 2,
      borderColor: 'rgba(255, 255, 255, 0.2)',
      iconKey: 'letter-s',
      iconSize: 190,
      iconColor: '#ffffff',
      iconGradient: false,
      text: 'STUDIO',
      fontFamily: 'Outfit',
      fontSize: 36,
      fontWeight: 700,
      textColor: '#e4e4e7',
      letterSpacing: 8,
      textUppercase: true,
      showTagline: true,
      tagline: 'CREATIVE AGENCY',
      taglineFontFamily: 'Outfit',
      taglineFontSize: 12,
      taglineColor: '#71717a',
      taglineLetterSpacing: 4,
      layout: 'icon-top',
    },
  },

  // 7. Arabesque Islamic Seal
  {
    id: 'arabesque-seal',
    nameAr: 'ختم النجمة الثمانية العربي',
    nameEn: 'Arabesque 8-Star Seal',
    category: 'arabesque',
    categoryLabelAr: 'زخارف إسلامية وعربية',
    categoryLabelEn: 'Arabesque & Islamic',
    config: {
      bgType: 'linear',
      bgColor1: '#064e3b',
      bgColor2: '#022c22',
      bgGradientAngle: 135,
      shapeMask: 'squircle',
      borderRadius: 50,
      borderWidth: 2.5,
      borderColor: '#34d399',
      innerGlow: true,
      innerGlowColor: '#6ee7b7',
      iconKey: 'arabesque-star',
      iconSize: 180,
      iconColor: '#6ee7b7',
      iconColor2: '#10b981',
      iconGradient: true,
      text: 'الأصيل',
      fontFamily: 'Cairo',
      fontSize: 46,
      fontWeight: 900,
      textColor: '#ecfdf5',
      letterSpacing: 2,
      showTagline: true,
      tagline: 'أصالة التراث ودقة المعايير',
      taglineFontFamily: 'Tajawal',
      taglineFontSize: 15,
      taglineColor: '#a7f3d0',
      taglineLetterSpacing: 1,
      layout: 'icon-top',
    },
  },

  // 8. Crescent Modern
  {
    id: 'crescent-modern',
    nameAr: 'شعار الهلال والنور',
    nameEn: 'Crescent & Radiance',
    category: 'arabesque',
    categoryLabelAr: 'زخارف إسلامية وعربية',
    categoryLabelEn: 'Arabesque & Islamic',
    config: {
      bgType: 'linear',
      bgColor1: '#0f172a',
      bgColor2: '#1e293b',
      bgGradientAngle: 90,
      shapeMask: 'circle',
      borderWidth: 2,
      borderColor: '#38bdf8',
      iconKey: 'crescent-moon',
      iconSize: 170,
      iconColor: '#38bdf8',
      iconColor2: '#818cf8',
      iconGradient: true,
      text: 'هِلال',
      fontFamily: 'Almarai',
      fontSize: 48,
      fontWeight: 800,
      textColor: '#ffffff',
      letterSpacing: 1,
      showTagline: true,
      tagline: 'منصة المعرفة والإلهام',
      taglineFontFamily: 'Tajawal',
      taglineFontSize: 15,
      taglineColor: '#94a3b8',
      layout: 'icon-top',
    },
  },

  // 9. Eco Nature Leaf
  {
    id: 'eco-pure',
    nameAr: 'بيئة الطبيعة الخضراء',
    nameEn: 'EcoLeaf Organic',
    category: 'eco',
    categoryLabelAr: 'طبيعة وبيئة',
    categoryLabelEn: 'Nature & Eco',
    config: {
      bgType: 'linear',
      bgColor1: '#064e3b',
      bgColor2: '#042f2e',
      bgGradientAngle: 150,
      shapeMask: 'squircle',
      borderRadius: 50,
      borderWidth: 2,
      borderColor: '#10b981',
      iconKey: 'leaf-eco',
      iconSize: 180,
      iconColor: '#34d399',
      iconColor2: '#059669',
      iconGradient: true,
      text: 'ECOGREEN',
      fontFamily: 'Outfit',
      fontSize: 40,
      fontWeight: 800,
      textColor: '#ffffff',
      letterSpacing: 3,
      showTagline: true,
      tagline: '100% ORGANIC & PURE',
      taglineFontFamily: 'Outfit',
      taglineFontSize: 13,
      taglineColor: '#6ee7b7',
      taglineLetterSpacing: 3,
      layout: 'icon-top',
    },
  },

  // 10. Ecommerce Store
  {
    id: 'ecommerce-cart',
    nameAr: 'متجر ومول التجارة',
    nameEn: 'Boutique Market Co.',
    category: 'ecommerce',
    categoryLabelAr: 'تجارة ومتاجر',
    categoryLabelEn: 'Ecommerce & Shop',
    config: {
      bgType: 'linear',
      bgColor1: '#831843',
      bgColor2: '#500724',
      bgGradientAngle: 135,
      shapeMask: 'squircle',
      borderRadius: 48,
      borderWidth: 2,
      borderColor: '#f472b6',
      iconKey: 'shopping-bag',
      iconSize: 170,
      iconColor: '#f472b6',
      iconColor2: '#fb7185',
      iconGradient: true,
      text: 'BOUTIQUE',
      fontFamily: 'Montserrat',
      fontSize: 40,
      fontWeight: 800,
      textColor: '#ffffff',
      letterSpacing: 4,
      showTagline: true,
      tagline: 'PREMIUM SHOPPING',
      taglineFontFamily: 'Outfit',
      taglineFontSize: 13,
      taglineColor: '#fbcfe8',
      taglineLetterSpacing: 3,
      layout: 'icon-top',
    },
  },

  // 11. Creative Art Studio
  {
    id: 'creative-prism',
    nameAr: 'استوديو الإبداع والفنون',
    nameEn: 'Prism Creative Studio',
    category: 'creative',
    categoryLabelAr: 'إبداع وفنون',
    categoryLabelEn: 'Creative & Art',
    config: {
      bgType: 'linear',
      bgColor1: '#4c1d95',
      bgColor2: '#1e1b4b',
      bgGradientAngle: 120,
      shapeMask: 'circle',
      borderWidth: 2,
      borderColor: '#c084fc',
      iconKey: 'triangle-prism',
      iconSize: 175,
      iconColor: '#e879f9',
      iconColor2: '#38bdf8',
      iconGradient: true,
      text: 'PRISM',
      fontFamily: 'Outfit',
      fontSize: 44,
      fontWeight: 900,
      textColor: '#ffffff',
      letterSpacing: 5,
      showTagline: true,
      tagline: 'VISUAL DESIGN LAB',
      taglineFontFamily: 'Outfit',
      taglineFontSize: 13,
      taglineColor: '#c084fc',
      taglineLetterSpacing: 4,
      layout: 'icon-top',
    },
  },

  // 12. Esports Gaming Shield
  {
    id: 'gaming-spartan',
    nameAr: 'درع الألعاب الإلكترونية',
    nameEn: 'Vanguard Esports',
    category: 'gaming',
    categoryLabelAr: 'ألعاب ورياضات إلكترونية',
    categoryLabelEn: 'Gaming & Esports',
    config: {
      bgType: 'linear',
      bgColor1: '#1c1917',
      bgColor2: '#0c0a09',
      bgGradientAngle: 180,
      shapeMask: 'shield',
      borderWidth: 3,
      borderColor: '#f97316',
      iconKey: 'spartan-helmet',
      iconSize: 170,
      iconColor: '#fb923c',
      iconColor2: '#ea580c',
      iconGradient: true,
      text: 'VANGUARD',
      fontFamily: 'Righteous',
      fontSize: 40,
      fontWeight: 700,
      textColor: '#ffffff',
      letterSpacing: 3,
      showTagline: true,
      tagline: 'ELITE ESPORTS SQUAD',
      taglineFontFamily: 'Outfit',
      taglineFontSize: 13,
      taglineColor: '#fb923c',
      taglineLetterSpacing: 3,
      layout: 'icon-top',
    },
  },

  // 13. Vintage Stamp Badge
  {
    id: 'badge-certified',
    nameAr: 'ختم الجودة والاعتماد',
    nameEn: 'Heritage Certified Stamp',
    category: 'badges',
    categoryLabelAr: 'شارات ودروع',
    categoryLabelEn: 'Badges & Seals',
    config: {
      bgType: 'linear',
      bgColor1: '#1e293b',
      bgColor2: '#0f172a',
      bgGradientAngle: 135,
      shapeMask: 'badge',
      borderWidth: 2,
      borderColor: '#38bdf8',
      iconKey: 'stamp-seal',
      iconSize: 170,
      iconColor: '#38bdf8',
      iconColor2: '#818cf8',
      iconGradient: true,
      text: 'VERIFIED',
      fontFamily: 'Montserrat',
      fontSize: 38,
      fontWeight: 800,
      textColor: '#ffffff',
      letterSpacing: 4,
      showTagline: true,
      tagline: 'AUTHENTIC QUALITY',
      taglineFontFamily: 'Outfit',
      taglineFontSize: 12,
      taglineColor: '#94a3b8',
      taglineLetterSpacing: 3,
      layout: 'icon-top',
    },
  },

  // 14. Modern Clean Gradient Pill
  {
    id: 'modern-wave-pill',
    nameAr: 'الموجة الحديثة الصافية',
    nameEn: 'Pure Wave Motion',
    category: 'minimal',
    categoryLabelAr: 'بسيط وأحادي',
    categoryLabelEn: 'Minimal & Monogram',
    config: {
      bgType: 'linear',
      bgColor1: '#0284c7',
      bgColor2: '#0369a1',
      bgGradientAngle: 90,
      shapeMask: 'squircle',
      borderRadius: 52,
      borderWidth: 2,
      borderColor: 'rgba(255, 255, 255, 0.3)',
      iconKey: 'wave-sine',
      iconSize: 170,
      iconColor: '#ffffff',
      iconGradient: false,
      text: 'WAVE',
      fontFamily: 'Outfit',
      fontSize: 44,
      fontWeight: 900,
      textColor: '#ffffff',
      letterSpacing: 4,
      showTagline: true,
      tagline: 'SEAMLESS FLOW',
      taglineFontFamily: 'Outfit',
      taglineFontSize: 13,
      taglineColor: '#bae6fd',
      taglineLetterSpacing: 3,
      layout: 'icon-top',
    },
  },
];
