/**
 * Downloads the app's typefaces into the repository, once, so nothing has to
 * be fetched from Google at run time.
 *
 * The app embeds font bytes into every exported SVG — that is what stops the
 * preview and the PNG from disagreeing about the typeface. Until now those
 * bytes were fetched from fonts.gstatic.com at the moment of export, which
 * means an export made offline, inside the native app, or from a network that
 * blocks Google silently loses its typeface: the export succeeds and the file
 * is wrong.
 *
 * Run: node scripts/fetch-fonts.mjs
 *
 * Idempotent. Re-run it to pick up new font versions; the output is committed,
 * so a normal build and CI never touch the network for this.
 *
 * Every family here is licensed under the SIL Open Font License, which permits
 * redistribution. The licence is written next to the files.
 */

import { mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

/** Kept in step with KNOWN_GOOGLE_FAMILIES in src/utils/fontEmbedder.ts. */
const FAMILIES = [
  'Cairo',
  'Tajawal',
  'Almarai',
  'IBM Plex Sans Arabic',
  'Outfit',
  'Montserrat',
  'Playfair Display',
  'Righteous',
  'Fira Code',
];

/** Matches REQUESTED_WEIGHTS in the embedder. Google collapses ones a family lacks. */
const WEIGHTS = [300, 400, 500, 600, 700, 800, 900];

/**
 * css2 serves woff2 only to a browser that advertises support. With Node's
 * default agent it answers with truetype, which is several times larger and
 * not what the embedder parses.
 */
const BROWSER_UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const OUT_DIR = path.resolve('public/fonts');

const slug = (value) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

async function getText(url) {
  const response = await fetch(url, { headers: { 'User-Agent': BROWSER_UA } });
  if (!response.ok) throw new Error(`${response.status} for ${url}`);
  return response.text();
}

async function getBytes(url) {
  const response = await fetch(url, { headers: { 'User-Agent': BROWSER_UA } });
  if (!response.ok) throw new Error(`${response.status} for ${url}`);
  return Buffer.from(await response.arrayBuffer());
}

/**
 * Splits a css2 response into its blocks, keeping the subset name Google
 * writes above each one — that name becomes the local file name, so the
 * output is legible rather than a wall of hashes.
 */
function parseBlocks(css) {
  const blocks = [];
  const pattern = /\/\*\s*([^*]+?)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let match;
  while ((match = pattern.exec(css)) !== null) {
    const [, subset, body] = match;
    const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(body)?.[1];
    const weight = /font-weight:\s*(\d+)/.exec(body)?.[1] ?? '400';
    if (url) blocks.push({ subset, body, url, weight });
  }
  return blocks;
}

async function main() {
  if (existsSync(OUT_DIR)) await rm(OUT_DIR, { recursive: true });
  await mkdir(OUT_DIR, { recursive: true });

  const sheet = [
    '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.',
    ' *',
    ' * Self-hosted so an export never depends on reaching Google. The',
    ' * unicode-range split is kept exactly as Google serves it, so a browser',
    ' * still downloads only the subsets the page actually needs.',
    ' */',
    '',
  ];

  let total = 0;
  let files = 0;

  for (const family of FAMILIES) {
    const url =
      `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}` +
      `:wght@${WEIGHTS.join(';')}&display=swap`;

    const css = await getText(url);
    const blocks = parseBlocks(css);
    if (blocks.length === 0) throw new Error(`No @font-face blocks for ${family}`);

    const seen = new Map();
    for (const block of blocks) {
      // One family can serve the same subset at several weights, and two
      // weights can share a file; key on the URL so a shared file is stored
      // once and referenced twice.
      let name = seen.get(block.url);
      if (!name) {
        name = `${slug(family)}-${block.weight}-${slug(block.subset)}.woff2`;
        const bytes = await getBytes(block.url);
        await writeFile(path.join(OUT_DIR, name), bytes);
        seen.set(block.url, name);
        total += bytes.length;
        files += 1;
      }

      sheet.push(
        `/* ${family} — ${block.subset} ${block.weight} */`,
        block.body.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(./${name})`),
        ''
      );
    }

    console.log(`${family.padEnd(22)} ${blocks.length} blocks`);
  }

  await writeFile(path.join(OUT_DIR, 'fonts.css'), sheet.join('\n'));

  const licence = await getText('https://openfontlicense.org/documents/OFL.txt').catch(() => null);
  await writeFile(
    path.join(OUT_DIR, 'LICENSE.txt'),
    [
      'The typefaces in this directory are redistributed under the SIL Open Font',
      'License, Version 1.1, which permits bundling them with an application.',
      '',
      FAMILIES.map((f) => `  - ${f}`).join('\n'),
      '',
      licence ? '\n' + licence : 'Full text: https://openfontlicense.org/documents/OFL.txt',
      '',
    ].join('\n')
  );

  console.log(`\n${files} files, ${(total / 1024 / 1024).toFixed(2)} MB in ${OUT_DIR}`);
}

await main();
